services:
  postgres:
    image: postgres:17-alpine
    container_name: vaultify-db
    environment:
      POSTGRES_USER: vaultify
      POSTGRES_PASSWORD: vaultify_password
      POSTGRES_DB: vaultify
    ports:
      - "5432:5432"
    volumes:
      - vaultify_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vaultify -d vaultify"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vaultify-redis
    ports:
      - "6379:6379"
    volumes:
      - vaultify_redisdata:/data
    command: redis-server --appendonly yes

volumes:
  vaultify_pgdata:
  vaultify_redisdata:
