// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        int64
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	Action    string
	KeyName   pgtype.Text
	IpAddress *netip.Addr
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	KekSalt   []byte
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ProjectMember struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Role      string
}

type Secret struct {
	ID             pgtype.UUID
	ProjectID      pgtype.UUID
	KeyName        string
	Environment    string
	EncryptedValue string
	Nonce          string
	CreatedBy      pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
