// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	KekSalt   []byte
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ProjectMember struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Role      string
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
