// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddProjectMemberParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Role      string
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, slug, kek_salt, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, kek_salt, created_by, created_at
`

type CreateProjectParams struct {
	Name      string
	Slug      string
	KekSalt   []byte
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Slug,
		arg.KekSalt,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.KekSalt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (project_id, key_name, environment, encrypted_value, nonce, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, key_name, environment, encrypted_value, nonce, created_by, updated_at, created_at
`

type CreateSecretParams struct {
	ProjectID      pgtype.UUID
	KeyName        string
	Environment    string
	EncryptedValue string
	Nonce          string
	CreatedBy      pgtype.UUID
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, createSecret,
		arg.ProjectID,
		arg.KeyName,
		arg.Environment,
		arg.EncryptedValue,
		arg.Nonce,
		arg.CreatedBy,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.KeyName,
		&i.Environment,
		&i.EncryptedValue,
		&i.Nonce,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets
WHERE id = $1
`

func (q *Queries) DeleteSecret(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSecret, id)
	return err
}

const getProjectById = `-- name: GetProjectById :one
SELECT id, name, slug, kek_salt, created_by, created_at FROM projects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProjectById(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectById, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.KekSalt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT project_id, user_id, role FROM project_members
WHERE project_id = $1 AND user_id = $2 LIMIT 1
`

type GetProjectMemberParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(&i.ProjectID, &i.UserID, &i.Role)
	return i, err
}

const getProjectsForUser = `-- name: GetProjectsForUser :many
SELECT p.id, p.name, p.slug, p.kek_salt, p.created_by, p.created_at FROM projects p
JOIN project_members pm ON p.id = pm.project_id
WHERE pm.user_id = $1
`

func (q *Queries) GetProjectsForUser(ctx context.Context, userID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.KekSalt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSecretByID = `-- name: GetSecretByID :one
SELECT id, project_id, key_name, environment, encrypted_value, nonce, created_by, updated_at, created_at FROM secrets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSecretByID(ctx context.Context, id pgtype.UUID) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretByID, id)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.KeyName,
		&i.Environment,
		&i.EncryptedValue,
		&i.Nonce,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, password_hash, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (user_id, project_id, action, key_name, ip_address)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	Action    string
	KeyName   pgtype.Text
	IpAddress *netip.Addr
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.UserID,
		arg.ProjectID,
		arg.Action,
		arg.KeyName,
		arg.IpAddress,
	)
	return err
}

const listAuditLogsByProject = `-- name: ListAuditLogsByProject :many
SELECT id, user_id, project_id, action, key_name, ip_address, created_at FROM audit_log
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByProjectParams struct {
	ProjectID pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListAuditLogsByProject(ctx context.Context, arg ListAuditLogsByProjectParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Action,
			&i.KeyName,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsByProject = `-- name: ListSecretsByProject :many
SELECT id, key_name, environment, updated_at, created_at
FROM secrets
WHERE project_id = $1
`

type ListSecretsByProjectRow struct {
	ID          pgtype.UUID
	KeyName     string
	Environment string
	UpdatedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListSecretsByProject(ctx context.Context, projectID pgtype.UUID) ([]ListSecretsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listSecretsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSecretsByProjectRow
	for rows.Next() {
		var i ListSecretsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyName,
			&i.Environment,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = COALESCE(NULLIF($2::text, ''), name),
    slug = COALESCE(NULLIF($3::text, ''), slug)
WHERE id = $1
RETURNING id, name, slug, kek_salt, created_by, created_at
`

type UpdateProjectParams struct {
	ID      pgtype.UUID
	Column2 string
	Column3 string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Column2, arg.Column3)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.KekSalt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secrets
SET encrypted_value = $2,
    nonce = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, key_name, environment, encrypted_value, nonce, created_by, updated_at, created_at
`

type UpdateSecretParams struct {
	ID             pgtype.UUID
	EncryptedValue string
	Nonce          string
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, updateSecret, arg.ID, arg.EncryptedValue, arg.Nonce)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.KeyName,
		&i.Environment,
		&i.EncryptedValue,
		&i.Nonce,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
