// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// #nosec G101
const createToken = `-- name: CreateToken :one
INSERT INTO api_tokens (user_id, project_id, name, token_hash, token_prefix, role, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, project_id, name, token_hash, token_prefix, role, last_used_at, expires_at, revoked, created_at
`

type CreateTokenParams struct {
	UserID      pgtype.UUID
	ProjectID   pgtype.UUID
	Name        string
	TokenHash   string
	TokenPrefix string
	Role        string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.UserID,
		arg.ProjectID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Role,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Role,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

// #nosec G101
const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, user_id, project_id, name, token_hash, token_prefix, role, last_used_at, expires_at, revoked, created_at FROM api_tokens
WHERE token_hash = $1 
  AND revoked = false
  AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Role,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

// #nosec G101
const listUserTokens = `-- name: ListUserTokens :many
SELECT id, user_id, project_id, name, token_hash, token_prefix, role, last_used_at, expires_at, revoked, created_at FROM api_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserTokens(ctx context.Context, userID pgtype.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listUserTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Role,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.Revoked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// #nosec G101
const softRevokeToken = `-- name: SoftRevokeToken :exec
UPDATE api_tokens
SET revoked = true
WHERE id = $1 AND user_id = $2
`

type SoftRevokeTokenParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) SoftRevokeToken(ctx context.Context, arg SoftRevokeTokenParams) error {
	_, err := q.db.Exec(ctx, softRevokeToken, arg.ID, arg.UserID)
	return err
}

// #nosec G101
const updateTokenLastUsed = `-- name: UpdateTokenLastUsed :exec
UPDATE api_tokens
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateTokenLastUsed, id)
	return err
}
